-- Modify "users" table
ALTER TABLE `users` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `email` varchar(255) NOT NULL, MODIFY COLUMN `password_hash` varchar(255) NOT NULL, MODIFY COLUMN `first_name` varchar(100) NOT NULL, MODIFY COLUMN `last_name` varchar(100) NOT NULL, MODIFY COLUMN `phone` varchar(20) NULL, MODIFY COLUMN `avatar_url` varchar(500) NULL, MODIFY COLUMN `preferred_currency` varchar(3) NOT NULL DEFAULT "BRL", MODIFY COLUMN `preferred_language` varchar(5) NOT NULL DEFAULT "pt-BR", MODIFY COLUMN `timezone` varchar(50) NOT NULL DEFAULT "America/Sao_Paulo", MODIFY COLUMN `role` enum('user','admin','premium') NOT NULL DEFAULT "user", MODIFY COLUMN `email_verified` bool NOT NULL DEFAULT 0, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP INDEX `email`;
-- Modify "audit_logs" table
ALTER TABLE `audit_logs` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NULL, MODIFY COLUMN `action` varchar(50) NOT NULL, MODIFY COLUMN `entity_type` varchar(50) NOT NULL, MODIFY COLUMN `entity_id` char(36) NULL, MODIFY COLUMN `ip_address` varchar(45) NULL, MODIFY COLUMN `user_agent` varchar(500) NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP FOREIGN KEY `audit_logs_ibfk_1`, ADD CONSTRAINT `fk_audit_logs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "bank_accounts" table
ALTER TABLE `bank_accounts` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `bank_accounts_chk_1`, DROP CONSTRAINT `bank_accounts_chk_2`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `name` varchar(100) NOT NULL, MODIFY COLUMN `bank_name` varchar(100) NULL, MODIFY COLUMN `bank_code` varchar(10) NULL, MODIFY COLUMN `account_type` enum('checking','savings','credit_card','investment','cash','other') NOT NULL, MODIFY COLUMN `account_number` varchar(50) NULL, MODIFY COLUMN `agency` varchar(20) NULL, MODIFY COLUMN `initial_balance` decimal(15,2) NOT NULL DEFAULT 0.00, MODIFY COLUMN `current_balance` decimal(15,2) NOT NULL DEFAULT 0.00, MODIFY COLUMN `closing_day` tinyint NULL, MODIFY COLUMN `due_day` tinyint NULL, MODIFY COLUMN `currency` varchar(3) NOT NULL DEFAULT "BRL", MODIFY COLUMN `color` varchar(7) NOT NULL DEFAULT "#10B981", MODIFY COLUMN `icon` varchar(50) NOT NULL DEFAULT "bank", MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `include_in_total` bool NOT NULL DEFAULT 1, MODIFY COLUMN `external_id` varchar(255) NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `bank_accounts_ibfk_1`, ADD CONSTRAINT `fk_bank_accounts_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "bank_integrations" table
ALTER TABLE `bank_integrations` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `bank_account_id` char(36) NULL, MODIFY COLUMN `provider` varchar(50) NOT NULL, MODIFY COLUMN `provider_account_id` varchar(255) NULL, MODIFY COLUMN `access_token_encrypted` text NULL, MODIFY COLUMN `refresh_token_encrypted` text NULL, MODIFY COLUMN `status` enum('pending','active','expired','revoked','error') NOT NULL DEFAULT "pending", MODIFY COLUMN `last_error` text NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP INDEX `bank_account_id`, ADD INDEX `fk_bank_integrations_bank_account` (`bank_account_id`), DROP FOREIGN KEY `bank_integrations_ibfk_1`, DROP FOREIGN KEY `bank_integrations_ibfk_2`, ADD CONSTRAINT `fk_bank_integrations_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_bank_integrations_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "categories" table
ALTER TABLE `categories` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NULL, MODIFY COLUMN `name` varchar(100) NOT NULL, MODIFY COLUMN `description` varchar(255) NULL, MODIFY COLUMN `type` enum('income','expense') NOT NULL, MODIFY COLUMN `color` varchar(7) NOT NULL DEFAULT "#6366F1", MODIFY COLUMN `icon` varchar(50) NOT NULL DEFAULT "wallet", MODIFY COLUMN `is_system` bool NOT NULL DEFAULT 0, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `categories_ibfk_1`, ADD CONSTRAINT `fk_categories_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "budgets" table
ALTER TABLE `budgets` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `budgets_chk_1`, DROP CONSTRAINT `budgets_chk_2`, DROP CONSTRAINT `budgets_chk_3`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `category_id` char(36) NULL, MODIFY COLUMN `name` varchar(100) NOT NULL, MODIFY COLUMN `spent_amount` decimal(15,2) NOT NULL DEFAULT 0.00, MODIFY COLUMN `period_type` enum('monthly','quarterly','yearly','custom') NOT NULL, MODIFY COLUMN `alert_threshold` decimal(5,2) NOT NULL DEFAULT 80.00, MODIFY COLUMN `alert_sent` bool NOT NULL DEFAULT 0, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `budgets_ibfk_1`, DROP FOREIGN KEY `budgets_ibfk_2`, ADD CONSTRAINT `fk_budgets_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_budgets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "email_verification_tokens" table
ALTER TABLE `email_verification_tokens` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `token_hash` varchar(255) NOT NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP FOREIGN KEY `email_verification_tokens_ibfk_1`, ADD CONSTRAINT `fk_email_verification_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "goals" table
ALTER TABLE `goals` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `goals_chk_1`, DROP CONSTRAINT `goals_chk_2`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `name` varchar(100) NOT NULL, MODIFY COLUMN `description` text NULL, MODIFY COLUMN `current_amount` decimal(15,2) NOT NULL DEFAULT 0.00, MODIFY COLUMN `icon` varchar(50) NOT NULL DEFAULT "target", MODIFY COLUMN `color` varchar(7) NOT NULL DEFAULT "#F59E0B", MODIFY COLUMN `priority` tinyint NOT NULL DEFAULT 1, MODIFY COLUMN `status` enum('in_progress','completed','cancelled') NOT NULL DEFAULT "in_progress", MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `goals_ibfk_1`, ADD CONSTRAINT `fk_goals_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "goal_contributions" table
ALTER TABLE `goal_contributions` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `goal_contributions_chk_1`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `goal_id` char(36) NOT NULL, MODIFY COLUMN `note` varchar(255) NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP FOREIGN KEY `goal_contributions_ibfk_1`, ADD CONSTRAINT `fk_goal_contributions_goal` FOREIGN KEY (`goal_id`) REFERENCES `goals` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "installments" table
ALTER TABLE `installments` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `installments_chk_1`, DROP CONSTRAINT `installments_chk_2`, DROP CONSTRAINT `installments_chk_3`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `bank_account_id` char(36) NOT NULL, MODIFY COLUMN `category_id` char(36) NULL, MODIFY COLUMN `description` varchar(255) NOT NULL, MODIFY COLUMN `total_installments` int NOT NULL, MODIFY COLUMN `paid_installments` int NOT NULL DEFAULT 0, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP INDEX `category_id`, ADD INDEX `fk_installments_category` (`category_id`), DROP FOREIGN KEY `installments_ibfk_1`, DROP FOREIGN KEY `installments_ibfk_2`, DROP FOREIGN KEY `installments_ibfk_3`, ADD CONSTRAINT `fk_installments_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_installments_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_installments_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "notifications" table
ALTER TABLE `notifications` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `type` enum('budget_alert','bill_reminder','goal_achieved','low_balance','transaction_alert','system') NOT NULL, MODIFY COLUMN `title` varchar(200) NOT NULL, MODIFY COLUMN `message` text NOT NULL, MODIFY COLUMN `is_read` bool NOT NULL DEFAULT 0, MODIFY COLUMN `sent_via` json NOT NULL DEFAULT (_utf8mb4'["in_app"]'), MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP FOREIGN KEY `notifications_ibfk_1`, ADD CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "password_reset_tokens" table
ALTER TABLE `password_reset_tokens` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `token_hash` varchar(255) NOT NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP FOREIGN KEY `password_reset_tokens_ibfk_1`, ADD CONSTRAINT `fk_password_reset_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "recurring_transactions" table
ALTER TABLE `recurring_transactions` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `recurring_transactions_chk_1`, DROP CONSTRAINT `recurring_transactions_chk_2`, DROP CONSTRAINT `recurring_transactions_chk_3`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `bank_account_id` char(36) NOT NULL, MODIFY COLUMN `category_id` char(36) NULL, MODIFY COLUMN `type` enum('income','expense') NOT NULL, MODIFY COLUMN `description` varchar(255) NOT NULL, MODIFY COLUMN `frequency` enum('daily','weekly','biweekly','monthly','quarterly','yearly') NOT NULL, MODIFY COLUMN `day_of_month` tinyint NULL, MODIFY COLUMN `day_of_week` tinyint NULL, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `auto_confirm` bool NOT NULL DEFAULT 0, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP INDEX `bank_account_id`, DROP INDEX `category_id`, ADD INDEX `fk_recurring_transactions_bank_account` (`bank_account_id`), ADD INDEX `fk_recurring_transactions_category` (`category_id`), DROP FOREIGN KEY `recurring_transactions_ibfk_1`, DROP FOREIGN KEY `recurring_transactions_ibfk_2`, DROP FOREIGN KEY `recurring_transactions_ibfk_3`, ADD CONSTRAINT `fk_recurring_transactions_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_recurring_transactions_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_recurring_transactions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "reports" table
ALTER TABLE `reports` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `name` varchar(100) NOT NULL, MODIFY COLUMN `type` enum('cash_flow','expense_by_category','income_vs_expense','budget_analysis','custom') NOT NULL, MODIFY COLUMN `schedule` enum('daily','weekly','monthly') NULL, MODIFY COLUMN `file_url` varchar(500) NULL, MODIFY COLUMN `is_active` bool NOT NULL DEFAULT 1, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `reports_ibfk_1`, ADD CONSTRAINT `fk_reports_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "transactions" table
ALTER TABLE `transactions` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `transactions_chk_1`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `bank_account_id` char(36) NOT NULL, MODIFY COLUMN `category_id` char(36) NULL, MODIFY COLUMN `type` enum('income','expense','transfer') NOT NULL, MODIFY COLUMN `description` varchar(255) NOT NULL, MODIFY COLUMN `notes` text NULL, MODIFY COLUMN `source` enum('manual','bank_sync','recurring') NOT NULL DEFAULT "manual", MODIFY COLUMN `is_paid` bool NOT NULL DEFAULT 0, MODIFY COLUMN `is_recurring` bool NOT NULL DEFAULT 0, MODIFY COLUMN `recurring_id` char(36) NULL, MODIFY COLUMN `installment_number` int NULL, MODIFY COLUMN `total_installments` int NULL, MODIFY COLUMN `installment_group_id` char(36) NULL, MODIFY COLUMN `attachment_url` varchar(500) NULL, MODIFY COLUMN `external_id` varchar(255) NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP COLUMN `auto_pay`, DROP INDEX `idx_transactions_source`, DROP FOREIGN KEY `transactions_ibfk_1`, DROP FOREIGN KEY `transactions_ibfk_2`, DROP FOREIGN KEY `transactions_ibfk_3`, ADD CONSTRAINT `fk_transactions_bank_account` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_transactions_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_transactions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "transfers" table
ALTER TABLE `transfers` COLLATE utf8mb4_0900_ai_ci, DROP CONSTRAINT `transfers_chk_1`, DROP CONSTRAINT `transfers_chk_2`, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `from_account_id` char(36) NOT NULL, MODIFY COLUMN `to_account_id` char(36) NOT NULL, MODIFY COLUMN `description` varchar(255) NULL, MODIFY COLUMN `from_transaction_id` char(36) NULL, MODIFY COLUMN `to_transaction_id` char(36) NULL, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, DROP INDEX `from_transaction_id`, DROP INDEX `to_transaction_id`, ADD INDEX `fk_transfers_from_transaction` (`from_transaction_id`), ADD INDEX `fk_transfers_to_transaction` (`to_transaction_id`), DROP FOREIGN KEY `transfers_ibfk_1`, DROP FOREIGN KEY `transfers_ibfk_2`, DROP FOREIGN KEY `transfers_ibfk_3`, DROP FOREIGN KEY `transfers_ibfk_4`, DROP FOREIGN KEY `transfers_ibfk_5`, ADD CONSTRAINT `fk_transfers_from_account` FOREIGN KEY (`from_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_transfers_from_transaction` FOREIGN KEY (`from_transaction_id`) REFERENCES `transactions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_transfers_to_account` FOREIGN KEY (`to_account_id`) REFERENCES `bank_accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `fk_transfers_to_transaction` FOREIGN KEY (`to_transaction_id`) REFERENCES `transactions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT `fk_transfers_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "user_sessions" table
ALTER TABLE `user_sessions` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `refresh_token_hash` varchar(255) NOT NULL, MODIFY COLUMN `device_info` varchar(500) NULL, MODIFY COLUMN `ip_address` varchar(45) NULL, MODIFY COLUMN `user_agent` varchar(500) NULL, MODIFY COLUMN `is_revoked` bool NOT NULL DEFAULT 0, MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP FOREIGN KEY `user_sessions_ibfk_1`, ADD CONSTRAINT `fk_user_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "user_settings" table
ALTER TABLE `user_settings` COLLATE utf8mb4_0900_ai_ci, MODIFY COLUMN `id` char(36) NOT NULL DEFAULT (uuid()), MODIFY COLUMN `user_id` char(36) NOT NULL, MODIFY COLUMN `notification_email` bool NOT NULL DEFAULT 1, MODIFY COLUMN `notification_push` bool NOT NULL DEFAULT 1, MODIFY COLUMN `notification_sms` bool NOT NULL DEFAULT 0, MODIFY COLUMN `budget_alerts` bool NOT NULL DEFAULT 1, MODIFY COLUMN `bill_reminders` bool NOT NULL DEFAULT 1, MODIFY COLUMN `bill_reminder_days` int NOT NULL DEFAULT 3, MODIFY COLUMN `weekly_summary` bool NOT NULL DEFAULT 1, MODIFY COLUMN `monthly_report` bool NOT NULL DEFAULT 1, MODIFY COLUMN `low_balance_alert` bool NOT NULL DEFAULT 1, MODIFY COLUMN `low_balance_threshold` decimal(15,2) NOT NULL DEFAULT 100.00, MODIFY COLUMN `theme` enum('light','dark','system') NOT NULL DEFAULT "system", MODIFY COLUMN `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, MODIFY COLUMN `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, DROP INDEX `user_id`, ADD UNIQUE INDEX `unique_user_settings` (`user_id`), DROP FOREIGN KEY `user_settings_ibfk_1`, ADD CONSTRAINT `fk_user_settings_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Drop "category_patterns" table
DROP TABLE `category_patterns`;
